### ISSUE TITLE
Enumerate WMI Event Subscriptions

### ISSUE THREAD

**Issue by mwjcomputing** [PSGumshoe/PSGumshoe#10]

**Comment by mattifestation** [comment]
Considerations:
1. __FilterToConsumerBinding, __EventFilter, and __EventConsumer classes exist in both the root/subscription and root/default namespace. We would want to capture both.
2. Are we going to want to keep this v2 compatible and only use Get-WmiObject? If we went that route, it would preclude us from using this functionality on PowerShell Core and Open Source PowerShell. I propose we use the Cim cmdlets. The downside is that it rules out v2 compat but it will ensure interoperability on every OS. It will also enable remote querying via WinRM or Dcom. This is obviously a larger discussion to be had about v2 compatibility for this project.
3. How do we want to handle __EventFilter and __EventConsumer instances for which there is no associated __FilterToConsumerBinding. From an IR perspective, I'm primarily interested in __FilterToConsumerBingin instances as they demonstrate actual persistence. Orphaned __EventFilter and __EventConsumer instances are certainly valuable artifacts, however. For the output of this function, I'd maybe propose a "Subscription" type comprised of a Binding, Filter, and Consumer property. In the case of an orphaned __EventFilter, I would propose returning a Subscription object (PSObject) but only it's Filter property would be populated. The same logic would apply for orphaned __FilterToConsumerBindings and __EventConsumers.
4. This also begs a larger discussion but is the intent for this to only run locally or do we want to support it to be run remotely - e.g. via a CimSession param?

**Comment by darkoperator** [comment]
Yes I would say locally and remotely supporting DCOM and CIM as options for remote
