### ISSUE TITLE
Strict v2 compat or cross-platform support?

### ISSUE THREAD

**Issue by mattifestation** [PSGumshoe/PSGumshoe#11]
We'll need to make a decision as to whether or not we will support v3+ with this module or if we need to limit ourselves to supporting v2 as the lowest common denominator. Personally, I think we should support v3 at a minimum as it would generally allow us to maintain better compatibility across all PowerShell paltforms - Windows PowerShell, PowerShell Core, and Open Source PowerShell. Additionally, I just love the language features of v3+. Obviously, by only supporting v3+, we would preclude the module from running on older systems. At some point, we're all going to need to ask ourselves when is the time to continue to support v2. For defensive code like this, I say that the time is now. My two cents.

**Comment by mattifestation** [comment]
Another two cents. Just as an example, I would be pretty dissatisfied if I couldn't run this module to investigate a potentially compromised Nano Server instance.

**Comment by jaredhaight** [comment]
What do you think about having the client side code be 3.0+ compatible but have any remote collection be compatible with Windows 7/2008 through either 2.0 or WMI or whatever. That would allow us to leverage 3.0 for crunching data while still being able to collect data from the widest variety of systems.

**Comment by jaredhaight** [comment]
Ahh, your comment on #10 answers that question.

**Comment by jaredcatkinson** [comment]
I think the best compromise is that all Server side code (the code that is being run on the machine that we control) is PSv3+ compatible, but all Client side code (the code that is being run on our network endpoint via PSRemoting) be PSv2 compatible.

**Comment by mattifestation** [comment]
So there would be some code that would be designed to run exclusively server-side? Having to distinguish between different compatible versions will likely confuse some users, IMO.

**Comment by jaredcatkinson** [comment]
Wouldn't it be silly to support Nano Server to the exclusion of default Windows 7? If this module doesn't support being run on Windows 7 (clients) then we are wasting our time.

The expectation being that the user should be running this from a modern OS, but may be targeting older OS. So use Get-CimInstance instead of Get-WmiObject, but don't target WMI classes that aren't available on every "target" OS.

Unless we want to provide some sort of compatibility notification. (This script will work when targeting PSv3+).

**Comment by matthastings** [comment]
I agree with @jaredcatkinson. While nano support would be great if that excludes supporting Windows 7 machines then I think we have to go with default Win 7 support

**Comment by mattifestation** [comment]
That's fine but there will need to be some thought put in to how you articulate the discrepancy. For example, would it make sense to break out two separate modules with server-side functionality and another for client-side functionality so that the module manifest can clearly distinguish what minimum version is required? As a user, if I'm going to be precluded from conducting an investigation from Nano or Linux/OSX (in the future), I'll want to know what stuff won't work.

**Comment by mattifestation** [comment]
I'm mainly playing devil's advocate here. One argument could be that by say choosing to use the Wmi cmdlets over the CIM cmdlets, that you're permanently precluding support on something like PowerShell Core whereas admins will not be precluded from upgrading to v3 or above.

**Comment by jaredcatkinson** [comment]
One solution is to check $PSVersionTable/$IsCoreCLR/$IsWindows/$IsLinux/$IsOSX and choose how you are going to accomplish the task from there. This appears to be how they address the problem in PS source (https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Security/security/Utils.cs#L112)
