### ISSUE TITLE
Traditional module or "PowerSploit model" of "weaponized", pre-packaged scripts?

### ISSUE THREAD

**Issue by mattifestation** [PSGumshoe/PSGumshoe#12]
This question ultimately comes down to: will you require installation of the module on the system being investigated or not?

If the decision is made to not require the module be present on the target system, then every exported function will have to be packaged with all of its dependencies included when used over PowerShell Remoting.

If the decision is made to require the module to be present on the system, then development of this module will be extremely straightforward and we can design it in such a way that we're leveraging the power of a proper PowerShell module.

**Comment by darkoperator** [comment]
good question I would prefer traditional module on this one. Lets do a reaction of thumbs up if traditional module or thumbs down if weaponize as a way to vote on it
