### ISSUE TITLE
Will some functions be designed to be run strictly remotely?

### ISSUE THREAD

**Issue by mattifestation** [PSGumshoe/PSGumshoe#13]
Or is it assumed that any function that supports something like -ComputerName or -CimSession can also be run locally?

Some of the comments in other issues indicate that there would be some server-side functionality but I'm not sure what functions would make sense to never have the option to be executed locally.

**Comment by darkoperator** [comment]
I would say no, remote and local when possible supporting WMI/CIM and Remoting again where it makes sense.
