### ISSUE TITLE
Restrieve Registry Key value and Information

### ISSUE THREAD

**Issue by darkoperator** [PSGumshoe/PSGumshoe#4]
Retrieve locally and remotely registry key properties for a host including timestamp information.

**Comment by mattifestation** [comment]
Unless you're wanting to write your own hive parsers, we'll want to pull in PowerForensics as a dependency in order to obtain timestamp info.

**Comment by jaredcatkinson** [comment]
What method would we use to include PowerForensics. If we can count on this module being on all systems, then PowerForensics integration is simple. If not, we could load the PowerForensic dll from a byte array and leverage the exposed APIs.

**Comment by darkoperator** [comment]
can PowerForensics pull that data via Remoting, Locally, CIM and/or DCOM?
